name: Build
description: Composite GitHub Action to build a brdgm.me application.

inputs:
  gh-site-deploy-pat:
    description: GH_SITE_DEPLOY_PAT secret
    required: true
  gh-site-deploy-username:
    description: GH_SITE_DEPLOY_USERNAME secret
    required: true
  gh-site-deploy-email:
    description: GH_SITE_DEPLOY_EMAIL secret
    required: true
  gh-site-deploy-name:
    description: GH_SITE_DEPLOY_NAME secret
    required: true
  stats-forms-url:
    description: VITE_STATS_FORM_URL variable
    required: false
  stats-field-mapping:
    description: VITE_STATS_FIELD_MAPPING variable
    required: false

outputs:
  app-deploy-name:
    description: Application deploy name
    value: ${{ steps.package_json.outputs.appDeployName }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v5

    - name: Read properties from package.json
      id: package_json
      uses: zoexx/github-action-json-file-properties@1.0.6
      with:
        file_path: package.json

    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: npm

    - run: npm ci
      shell: bash

    - run: npm run lint
      shell: bash

    - run: npm run test:unit
      shell: bash

    - run: npm run build
      shell: bash
      env:
        VITE_STATS_FORM_URL: ${{ inputs.stats-forms-url }}
        VITE_STATS_FIELD_MAPPING: ${{ inputs.stats-field-mapping }}

    - name: Copy to Site
      uses: cpina/github-action-push-to-another-repository@v1.7.3
      env:
        API_TOKEN_GITHUB: ${{ inputs.gh-site-deploy-pat }}
      with:
        source-directory: dist
        destination-repository-username: brdgm
        destination-repository-name: brdgm.github.io
        destination-github-username: ${{ inputs.gh-site-deploy-username }}
        user-email: ${{ inputs.gh-site-deploy-email }}
        user-name: ${{ inputs.gh-site-deploy-name }}
        target-branch: main
        commit-message: deploy ${{ steps.package_json.outputs.appDeployName }} ${{ steps.package_json.outputs.version }}
        target-directory: ${{ steps.package_json.outputs.appDeployName }}
